
all:
	make -C submit
	make -C chmod
	make -C demo

clean:
	make -C submit clean
	make -C chmod clean
	make -C demo clean

install:
	make -C submit install
	make -C chmod install
	make -C demo install
